dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            entities:
                App\Entity\User: ~
                App\Entity\AuditoriaInterna: ~
                App\Entity\Cargo: ~
