vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix:         /Sabio/public/uploads/user/images
            upload_destination: '%kernel.project_dir%/public/uploads/user/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        personal_image:
            uri_prefix:         /Sabio/public/uploads/personal/images
            upload_destination: '%kernel.project_dir%/public/uploads/personal/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
